### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by YangYangTaoTao** [pddata/PDMotorDB#1]
您好，请问我哪里可以申请这个数据集呢？谢谢！

**Comment by pddata** [comment]
> 您好，请问我哪里可以申请这个数据集呢？谢谢！

Hello, thanks for interests in our work. We are removing patient privacy now in dataset. After finishing that, we will upload a license agreement and you sign it and sent it to us. Then we will send you the full dataset. Thanks.

**Comment by pddata** [comment]
The application channel is open.
